name: Deploy Service on Portainer

on:
  workflow_dispatch:
    inputs:
      webhook_url:
        description: "Portainer Webhook URL"
        required: true
      tag:
        description: "Image tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Webhook with new tag
        run: |
          echo "Redeploying service with tag $URL?tag=$TAG..."
          curl -X POST "$URL?tag=$TAG"
        env:
          URL: ${{ github.event.inputs.webhook_url }}
          TAG: ${{ github.event.inputs.tag }}
