name: Create TXT on Tag

on:
  push:
    tags:
      - "*" # Trigger khi có bất kỳ tag nào

jobs:
  create-txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H an.bhieu.com >> ~/.ssh/known_hosts

      - name: Create TXT on server
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          ssh vps@an.bhieu.com "echo 'Tag: $TAG_NAME created at $(date)' > /home/vps/tag-files/$TAG_NAME.txt"
